---
title: "Multiple Linear Regression for Low Code Study"
author: "TW"
format: 
    html: 
      #mainfont: Times New Roman
      fontfamily: libertinus
      fontsize: 10pt
editor: visual
---

## Multiple Linear Regression for Low Code Study
Using cleaned data from Forrester's Low Code Study, the code below uses regression models to identify
the non-cost variables (predictors) that are the most predictive of cost variables (targets). The results
will inform the development of a 3-class (low/median/high) 'Complexity' designation which will be used
to predict costs for those outside of the study.

The cost variable(s) in raw form were set as the target instead of the categorical 'Complexity'
interpretation of costs since using the latter would obscure the ultimate target (costs). If targeting
a categorical variable, logistic regression or classification approaches might be better. Since we're 
targeting a scaled quantitative variable, we're using multiple linear regression here (the lm() function).
Alternatives are feature selection (see stepwise, LASSO, or random forest) or regularization to identify
the most important predictors and avoid overfitting.


# Import and view cleaned data file
library(readxl)
RegressionData <- read_excel("C:/Users/tmail/Desktop/Piedmont/ForresterLowCodeStudy/RegressionData.xlsx",
sheet = "Data")
View(RegressionData)


See 'SelectTarget&Predictors' tab in file above to view groups of predictors (A/B/C/D). Care was taken
to minimize overfitting and collinearity. Initial fitting of multiple linear regression model:


# Fit a multiple linear regression model by group of predictors (A-H)
modelA <- lm(TOT5YrCosts ~ NumOneTimeCostCatgsQ1 + CountryS1 + IndustryS4 + DevTypeS15 + AnnRevS2 + 
ExpWSolutionS12, data = RegressionData)
 
modelB <- lm(TOT5YrCosts ~ ImplTimeMosS13 + NumHrsQ3cm + NumRecrrCostCatgsQ10 + NumRcrrInfrCatgsQ23 +
NumEesS3, data = RegressionData)
 
modelC <- lm(TOT5YrCosts ~ NumOneTimeTrngCostCatgsQ5 + DETrainQ6axhrs + NumRecrrIntTrainCatgsQ18 +
NumLicensesS14 + NumAutoWkflowsS16, 
data = RegressionData)
 
modelD <- lm(TOT5YrCosts ~ SolutionS10 + NumHrsQ3id + NumRecrrIntLabCatgsQ13 + RecrrIntLabHrsQ14 +
NumTotDevs, data = RegressionData)
 
# modelE <- lm(TOT5YrCosts ~ ImplTimeMosS13 + NumRecrrCostCatgsQ10 + NumRcrrInfrCatgsQ23 + NumEesS3,
# data = RegressionData)
# 
# modelF <- lm(TOT5YrCosts ~ NumOneTimeTrngCostCatgsQ5 + NumRecrrIntTrainCatgsQ18 + SolutionS10 +
# NumAutoWkflowsS16, data = RegressionData)
# 
# modelG <- lm(TOT5YrCosts ~ ExpWSolutionS12 + NumLicensesS14 + SolutionS10 + NumRecrrIntLabCatgsQ13 +
# NumRecrrIntLabCatgsQ13, data = RegressionData)
# 
# modelH <- lm(TOT5YrCosts ~ NumOneTimeCostCatgsQ1 + CountryS1 + IndustryS4 + DevTypeS15 + NumTotDevs +
# ExpWSolutionS12, data = RegressionData)


View summaries:

# View a summary of model results
summary(modelA)
#summary(modelB)
#summary(modelC)
#summary(modelD)

Saving model output:

# Write the captured output to file
writeLines(capture.output(summary(modelA)), "Regression_Tot5YrCosts_A.txt")
writeLines(capture.output(summary(modelB)), "Regression_Tot5YrCosts_B.txt")
writeLines(capture.output(summary(modelC)), "Regression_Tot5YrCosts_C.txt")
writeLines(capture.output(summary(modelD)), "Regression_Tot5YrCosts_D.txt")
# writeLines(capture.output(summary(modelE)), "Regression_Tot5YrCosts_E.txt")
# writeLines(capture.output(summary(modelF)), "Regression_Tot5YrCosts_F.txt")
# writeLines(capture.output(summary(modelG)), "Regression_Tot5YrCosts_G.txt")
# writeLines(capture.output(summary(modelH)), "Regression_Tot5YrCosts_H.txt")


Using stepwise selection model to help identify a subset of the most relevant predictors from A/B/C/D:

# Perform stepwise selection using BIC as the criterion (B-D include hrs/ees data with too many blanks
for step() function)

step_modelA <- step(modelA, direction = "both", k = log(nrow(RegressionData)), trace = FALSE)
step_modelE <- step(modelE, direction = "both", k = log(nrow(RegressionData)), trace = FALSE)
step_modelF <- step(modelF, direction = "both", k = log(nrow(RegressionData)), trace = FALSE)
step_modelG <- step(modelG, direction = "both", k = log(nrow(RegressionData)), trace = FALSE)
step_modelH <- step(modelH, direction = "both", k = log(nrow(RegressionData)), trace = FALSE)


Saving stepwise selection model output:

# Write the captured output to a file 
writeLines(capture.output(summary(step_modelA)), "Regression_Tot5YrCosts_step_A.txt) 
writeLines(capture.output(summary(step_modelE)), "Regression_Tot5YrCosts_step_E.txt) 
writeLines(capture.output(summary(step_modelF)), "Regression_Tot5YrCosts_step_F.txt) 
writeLines(capture.output(summary(step_modelG)), "Regression_Tot5YrCosts_step_G.txt) 
writeLines(capture.output(summary(step_modelH)), "Regression_Tot5YrCosts_step_H.txt) 


Informed by the results above, these are the final groupings of predictors that will inform an updated
(more predictive) "Complexity" designation:


# fitting multiple regression model
mod_Rev.Devs.Wkfls <- lm(TOT5YrCosts ~ FiveYrRev + NumTotDevs + NumAutoWkflowsS16, data = RegressionData)

mod_Rev.Sol.Exp.Wkfls <- lm(TOT5YrCosts ~ FiveYrRev + SolutionS10 + ExpWSolutionS12 + NumAutoWkflowsS16,
data = RegressionData)

mod_Lics.Sol.PDev <- lm(TOT5YrCosts ~ NumLicensesS14 + SolutionS10 + NumProDevsS17, data = RegressionData)

mod_Devs.Sol.Exp <- lm(TOT5YrCosts ~ NumTotDevs + SolutionS10 + ExpWSolutionS12, data = RegressionData)

mod_Ees.Sol.Wkfls <- lm(TOT5YrCosts ~ NumEesS3 + SolutionS10 + NumAutoWkflowsS16, data = RegressionData)

mod_Ees.Sol.Lics <- lm(TOT5YrCosts ~ NumEesS3 + SolutionS10 + NumLicensesS14, data = RegressionData)

mod_Ees.Lics.Devs.Wkfls <- lm(TOT5YrCosts ~ NumEesS3 + NumLicensesS14 + NumTotDevs + NumAutoWkflowsS16,
data = RegressionData)

mod_Ees.Lics.Devs <- lm(TOT5YrCosts ~ NumEesS3 + NumLicensesS14 + NumTotDevs, data = RegressionData)


Saving model output:

# Write the output to file
writeLines(capture.output(summary(mod_Devs.Sol.Exp)), "Regression_Tot5YrCosts_DSX.txt")
writeLines(capture.output(summary(mod_Ees.Sol.Wkfls)), "Regression_Tot5YrCosts_ESW.txt")
writeLines(capture.output(summary(mod_Lics.Sol.PDev)), "Regression_Tot5YrCosts_LSP.txt")
writeLines(capture.output(summary(mod_Rev.Devs.Wkfls)), "Regression_Tot5YrCosts_RDW.txt")
writeLines(capture.output(summary(mod_Rev.Sol.Exp.Wkfls)), "Regression_Tot5YrCosts_RSXW.txt")
writeLines(capture.output(summary(mod_Ees.Sol.Lics)), "Regression_Tot5YrCosts_ESL.txt")
writeLines(capture.output(summary(mod_Ees.Lics.Devs.Wkfls)), "Regression_Tot5YrCosts_ELDW.txt")
writeLines(capture.output(summary(mod_Ees.Lics.Devs)), "Regression_Tot5YrCosts_ELD.txt")
